### ISSUE TITLE
Footer Design

### ISSUE THREAD

**Issue by nartehi** [nartehi/TiC-Foundation#8]
The footer looks a bit unorganized. Add some hovering effect to the links and also add the location google map to the footer. Add a cursor effect to the links so that when a user hover over the links there is an effect and the cursor shows.

**Comment by nartehi** [comment]
@CallOfBeauty is working on this issue now

**Comment by CallOfBeauty** [comment]
Consolidation of Issue #11 , Footer navigation bars need scrolling effect

**Comment by CallOfBeauty** [comment]
Working on it
-Dimitrios

**Comment by CallOfBeauty** [comment]
I added the maps feature and organized it a little differently, removing the logo. The navbars have a hovering effect now, the same as the navbars on top the cursor effect code is in there too. Let me know if you like it

**Comment by CallOfBeauty** [comment]
If experiencing any issues, npm install @fortawesome/free-brands-svg-icons

**Comment by nartehi** [comment]
The new feature added looks really great. Thank you. We just have to resize the map, but this is an easy fix.
